### ISSUE TITLE
Error in search

### ISSUE THREAD

**Issue by oliviachock** [spicygreenbook/greenbook#1]
When typing things in the search bar and clicking search, it takes me to a page that says "An unexpected error has occurred." Even if there are no matches, I would expect the page to say "Sorry, no searches were found for [location/genre searched]".

**Comment by pleaseshutup** [comment]
This is now fixed, thank you so much for reporting it.

The bug was any time a search had more than one word. It should show you matching results or the message relaying that nothing matched the search.
