### ISSUE TITLE
Ranch Side Cafe

### ISSUE THREAD

**Issue by Charminglady** [spicygreenbook/greenbook#10]
South of the Border Menu -  Last entree description needs to be corrected. "Seasoned chicken or steak grilled with onions, chopped tomatoes, and bell peppers. Served with Mexican rice, refried beans, corn tortillas, fresh guacamole, and sour cream. **r paragraph here.**.

On some of the menus the entrees are a little hard to distinguish from the descriptions.  Maybe make the entrees bold, italic, or both.

**Comment by pleaseshutup** [comment]
Hello, if this issue is on spicygreenbook.com please let us know which URL on our site so we can fix it.

If it is not on spicygreenbook.com and on another website (such as the website of one of our listings) we cannot do anything to fix it. We do not manage websites for our listings.

**Comment by pleaseshutup** [comment]
Sorry, this issue isn't on spicygreenbook.com so we can't fix it.
