### ISSUE TITLE
[Contact Page] Contact Form doesn't load in Safari (Version 14.0 (15610.1.28.1.9, 15610))

### ISSUE THREAD

**Issue by prabackar** [spicygreenbook/greenbook#258]
Works fine in Firefox 80.0.1 (64-bit) and Chrome Version 85.0.4183.102 (Official Build) (64-bit)
<img width="1428" alt="Screen Shot 2020-09-17 at 10 41 47 AM" src="https://user-images.githubusercontent.com/931394/93507843-21f95e00-f8d3-11ea-98cb-a88007404c38.png">

**Comment by pleaseshutup** [comment]
This is fixed:
https://github.com/spicygreenbook/greenbook/issues/14

Thanks!
