### ISSUE TITLE
PowR Meals includes duplicate "thank you" details

### ISSUE THREAD

**Issue by badstink** [spicygreenbook/greenbook#285]
At the bottom of the About section, the photographer thank you information is listed twice:

Thank you to professional photographer Marlin Salazar for donating your time and talent providing the photos on this page.
likethefishmedia.com@marlin_like_the_fish

Thank you to professional photographer Marlin Salazar for donating your time and talent providing the photos on this page.
likethefishmedia.com@marlin_like_the_fish

**Comment by pleaseshutup** [comment]
This is fixed in the CMS, Thanks!
