### ISSUE TITLE
Home Page Menu on Mobile Inconsistent Placement with Other Pages

### ISSUE THREAD

**Issue by skifreetony** [spicygreenbook/greenbook#3]
![Screen Shot 2020-07-05 at 10 38 49 PM](https://user-images.githubusercontent.com/12958581/86559382-ad886300-bf10-11ea-86b6-047f53cd8c25.png)

**Comment by pleaseshutup** [comment]
New design coming, home page text larger than sub page header/back arrow. home page is different than sub-pages. Not concerned about this.
