### ISSUE TITLE
"Search / Cuisine" drop down on home page should be alphabetically sorted or logically sorted 

### ISSUE THREAD

**Issue by selinger2211** [spicygreenbook/greenbook#315]
The "Search / Cuisine" drop down on home page should be alphabetically sorted or logically sorted? 

There are also some items in there that don't make sense, for example one of the option in the drop down is 6901

<img width="1087" alt="Screen Shot 2020-09-17 at 11 04 55 AM" src="https://user-images.githubusercontent.com/4119478/93510275-c67c9f80-f8d5-11ea-816a-1189796477b6.png">

**Comment by pleaseshutup** [comment]
This is done.
