### ISSUE TITLE
Ladie Kakes Social Link Broken

### ISSUE THREAD

**Issue by candersonj61** [spicygreenbook/greenbook#353]
The instagram link for Ladie Kakes no longer works and goes to an error page.

https://spicygreenbook.com/biz/ladie-kakes

**Comment by Dorkjedi** [comment]
unable to duplicate - I click the instagram link and am taken to the correct instagram account page 

![image](https://user-images.githubusercontent.com/2332289/93511919-875c4780-f8f1-11ea-9493-73224c59ff87.png)
