### ISSUE TITLE
Business listings

### ISSUE THREAD

**Issue by lthamizhmani** [spicygreenbook/greenbook#363]
1. Some business listing's pages have text in italics, some are regular. Could make formatting consistent for better look & feel.
2. Would be better to sort businesses by alphabetical order of name. This could be done in the default view before search & after search results are returned.
3. Smack'd has no tags. Might be better to remove the tag icon if there's no info available.

**Comment by pleaseshutup** [comment]
Ordering is contextual, by search and/or by proximity. If not search/proximity we have our own ordering system in our CMS to try to get newer listings pushed up first.

Thanks for the feedback.
