### ISSUE TITLE
Menu link is incorrect - https://spicygreenbook.com/biz/beyond-vegan-eats

### ISSUE THREAD

**Issue by rlewis02** [spicygreenbook/greenbook#400]
Link listed in SGB:
https://beyondveganlifestyle.comhttps//beyondvegan.goprep.com/customer/menu

Should be: 
https://beyondvegan.goprep.com/customer/menu

**Comment by Dorkjedi** [comment]
Can duplicate - the Online Ordering menu link is wrong

![image](https://user-images.githubusercontent.com/2332289/93513516-f9359080-f8f3-11ea-806b-085ebd028539.png)

**Comment by pleaseshutup** [comment]
Fixed in the CMS, Thanks!
