### ISSUE TITLE
Broken webpage link for Flower and Sugar: https://spicygreenbook.com/biz/flour-and-sugar

### ISSUE THREAD

**Issue by jlb396** [spicygreenbook/greenbook#406]
check link for flower and sugar, below is what populates when clicking the current link:

![Screen Shot 2020-09-17 at 2 40 46 PM](https://user-images.githubusercontent.com/71458271/93513430-d60ae100-f8f3-11ea-87bf-99932febd25c.png)

**Comment by Dorkjedi** [comment]
Can duplicate - Looks liek there is an extra 'https://' at the end of the links to the web site and online ordering

![image](https://user-images.githubusercontent.com/2332289/93514804-a2c95180-f8f5-11ea-9d65-00b9d7299baa.png)

**Comment by pleaseshutup** [comment]
Fixed in the CMS

Thanks!
