### ISSUE TITLE
sitemap.xml using incorrect domain (lunarcrush.com)

### ISSUE THREAD

**Issue by c0ldbr3w** [spicygreenbook/greenbook#413]
Link: https://spicygreenbook.com/sitemap.xml

Expected behavior:
The sitemap.xml doc should provide a crawler-friendly list of resources on a site. Each entry should include a valid "loc" for each "url" object. For this site, each "loc" should be a resource on spicygreenbook.com.

Current behavior:
_All_ links in sitemap.xml specify "lunarcrush.com" as the domain.
Example:
```
<url>
  <loc>https://lunarcrush.com/biz/rodneys-ribs</loc>
  <lastmod>2020-09-17</lastmod>
  <changefreq>always</changefreq>
  <priority>1.0</priority>
</url>
```
Note: the path appears to be accurate, so the issue is limited to the domain. For instance, the above example correctly includes "/biz/rodneys-ribs".

**Comment by pleaseshutup** [comment]
Thanks @Dorkjedi for the fix
