### ISSUE TITLE
Contact Us issue

### ISSUE THREAD

**Issue by lthamizhmani** [spicygreenbook/greenbook#487]
Steps to reproduce:
1. Click on Contact Us link in Hamburger menu on the right. User is taken to the Contact Us page. No form is shown under 'Contact'
3. Reload the page. Now a contact us form is shown. Form should be shown in step 1 & shouldn't need a page reload.

**Comment by pleaseshutup** [comment]
This is fixed
https://github.com/spicygreenbook/greenbook/issues/14

Thanks!
