### ISSUE TITLE
Show all the contact methods, website info on the list page 

### ISSUE THREAD

**Issue by karenc-vm** [spicygreenbook/greenbook#504]
![image](https://user-images.githubusercontent.com/71466357/93527021-23d01b00-f8ed-11ea-8065-8452ee46854c.png)
![image](https://user-images.githubusercontent.com/71466357/93527030-2763a200-f8ed-11ea-8a43-83874280d4f0.png)

**Comment by pleaseshutup** [comment]
The entire row is clickable for a listing to take you to the detail of the listing. We do not intend to have multiple clickable areas in the list. We encourage a user to visit a listing to see all of the content we have curated for it.
