### ISSUE TITLE
[Bug] Search requires multiple inputs to update the map

### ISSUE THREAD

**Issue by mattgraham1995** [spicygreenbook/greenbook#532]
Steps to reproduce:
1. Visit https://spicygreenbook.com/search
2. In the location input box, type in a zip code that will have no results (Chicago for example could be 60607)
3. Click the search button
4. After the map loads to Chicago and shows no results, type in another location with no results (64106 is the zip code for Kansas City)
5. Click the search button
6. The map will not always refresh and move to the new location. It will occasionally, but not always.

**Comment by pleaseshutup** [comment]
Unable to replicate.
