### ISSUE TITLE
Map integration

### ISSUE THREAD

**Issue by vartikaarora** [spicygreenbook/greenbook#535]
The map isn't showing the exact location for D Lo’s Kitchen. There is a radius for most of LA instead.

**Comment by vartikaarora** [comment]
Mile High Cheesecakes also not showing location on map.

**Comment by pleaseshutup** [comment]
Locations with a radius do not have an address, they have a coverage area because they are trucks or mobile shops that move to many locations within an area. Thanks for your suggestion.
