### ISSUE TITLE
Contact Us - Photography email to be link?

### ISSUE THREAD

**Issue by gmpetersen** [spicygreenbook/greenbook#560]
Having this email as a url to prompt a message in gmail, y! mail etc. would help remove the extra steps or copy paste.  I know it sounds silly, but sometimes even the smallest hurdle to the end user can lead to drop-off!

![image](https://user-images.githubusercontent.com/71515518/93617386-c25e8980-f98a-11ea-9870-b523b3467c1f.png)

**Comment by pleaseshutup** [comment]
Fixed.
