### ISSUE TITLE
Food Search - Directions to the food

### ISSUE THREAD

**Issue by gmpetersen** [spicygreenbook/greenbook#561]
The map feature is great!  However, it would be great to be able to calculate the best way to get there either by walking, public transit, or car.  Clicking the pin points on the map shows the image used to market the food establishment, this could be used to open a mapping function for users to figure out how to visit the business.

![image](https://user-images.githubusercontent.com/71515518/93618609-5b41d480-f98c-11ea-9073-15b5009bbbcb.png)

**Comment by pleaseshutup** [comment]
If a listing has an address you can click on the address for directions.
Some listings are mobile/food trucks and do not have a stable address and cannot be navigated to. Their location changes and/or they go to you.
