### ISSUE TITLE
View All Listings Page Map

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook#6]
The images on the map are broken. They don't show up when you click on the icon on the map.

**Comment by pleaseshutup** [comment]
seems to all load fine for me. 

please give me steps to reproduce and which device/browser you are using.

**Comment by pleaseshutup** [comment]
> The images on the map are broken. They don't show up when you click on the icon on the map.

seems to all load fine for me.

please give me steps to reproduce and which device/browser you are using.

**Comment by danilobatson** [comment]
> please give me steps to reproduce and which device/browser you are using.

Scratch that, I was unable to reproduce as well. Was using chrome on a laptop.
