### ISSUE TITLE
Mile High Cheesecake

### ISSUE THREAD

**Issue by dmkhan6** [spicygreenbook/greenbook#7]
Typos: an uncle who **is was** a flight attendant; of my **family lives** should be **family's lives**; **living in Los Angeles** inner-city should be 'living **in the Los** Angeles inner-city;  beaches, **desserts** or mountains should be **deserts**; Mile High **Cheesecakes** vision should be **Cheesecakes's**; for **unprivileged** youth, do you mean **underprivileged**?  you should check the punctuation of the whole piece to make it easier to read.

**Comment by danilobatson** [comment]
Resolved typos
