### ISSUE TITLE
Camisha's Cakes

### ISSUE THREAD

**Issue by Charminglady** [spicygreenbook/greenbook#8]
When CAKE MENU is clicked, instead of opening to a menu it goes back to the top of the screen which displays the order now box. The order now box requests potential customer's name, email, due date with a comment box to tell about the cake. A more detailed order form with would be more helpful (ex. cake size, flavors, frosting type, filling, occasion.

**Comment by pleaseshutup** [comment]
Is this issue on the spicygreenbook.com website or another website (such as the website of one of our listings) that we do not manage?

**Comment by pleaseshutup** [comment]
Sorry, this issue isn't on spicygreenbook.com so we can't fix it.
